### PR TITLE
Add recipient field

### PR DESCRIPTION
**Pull request by tiananguyen**
For a new feature to the direct messages, I added a recipient field to Message.java, Datastore.java, and MessageServlet.java. Message.java stores the recipient field in the Message class. MessageServlet.java passes the recipient from the client to the sever. Datastore.java stores the recipient in our data.

### CODE REVIEW

**Comment by MCharming98** [comment]
This looks good, make sure you solve the merge conflict while getting updates from master

**Review by alyssa-lau — APPROVED** [review]
This looks good to merge, passes the automated checks.

**Review by maksymko — COMMENTED** [review]
We did talk about using rebase instead of merge, didn't we?

**Comment by tiananguyen** [comment]
Oh right, we did. I totally forgot about that. My apologies!

**Pull request merged**
