### PR TITLE
Added a new stats.html page

### PR DESCRIPTION
**Pull request by alyssa-lau**
Adding a html page, will possibly update later to separate the javascript from the html file

### CODE REVIEW

**Review by tiananguyen — COMMENTED** [review]
Everything looks good! One thing though, for the index.html, did you mean to add the "Hello World" or was that just for playing around and testing?

**Comment by MCharming98** [comment]
I think you should not make changes to the index.html, I know the setup tells you to change the welcome message to hello world but I think we just keep it as before for the project.

One style thing that can be improved is to separate the javascript code from html page, but it's up to you.

**Comment by maksymko** [comment]
@alyssa-lau just a word of caution: please don't use "Update branch" button. Use the process described here instead: https://github.com/maksymko/codeu-starter-project/wiki/Rebasing

**Comment by alyssa-lau** [comment]
Reverted index.html to version before project.

**Review by MCharming98 — APPROVED** [review]
Looks good to me!

**Pull request merged**
